import { act, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { api, ApiError, setActor } from "../api";
import { setLanguage } from "../i18n";
import { codePointSlice, elementKey, type NativeItemResult, type NativeSourcePage } from "../native";
import { ItemReview } from "../views/ReviewWorkspace";
import { defaultResultTable } from "../views/ResultStage";
import { clearDraft, draftKey, getDraft, hydrateDrafts, resetDrafts, setNativeField, setNativeSources, settleNativeDraft } from "./drafts";
import { NativeFactPanel, nativeSaveBody } from "./NativeFactPanel";
import { loadNativeSource } from "./NativeReview";
import { NativeSourceViewer } from "./NativeSourceViewer";
import fixtures from "./native109.fixture.json";

// Generated by W1 from validated Python K0 models; no provider calls or live data.
const original = fixtures.items.complete as NativeItemResult;
const textSource = fixtures.source_pages.text as NativeSourcePage;
const cellSource = fixtures.source_pages.cells as NativeSourcePage;
const clone = <T,>(x: T): T => JSON.parse(JSON.stringify(x));
const key = draftKey(original.run_id, original.item_id);
const fact = original.native_facts[0];
beforeEach(async () => { vi.restoreAllMocks(); resetDrafts(); await setLanguage("en"); setActor("Synthetic reviewer"); });

describe("native saved-source contract", () => {
  it("uses Unicode code points and leaves source markup inert", () => {
    expect(codePointSlice("A😀\u0151Z", 1, 3)).toBe("😀\u0151");
    const source = clone(textSource);
    const element = source.elements.find((e) => e.locator.kind === "text")!;
    if (element.locator.kind !== "text") throw new Error("Fixture needs text");
    source.texts[element.locator.text_sha256] = "😀<script>alert(1)</script>\u0151";
    element.locator.end = Array.from(source.texts[element.locator.text_sha256]).length;
    const { container } = render(<NativeSourceViewer source={source} selected={null} citation={null} onPick={() => {}} />);
    expect(container.querySelector("script")).toBeNull();
    expect(container.textContent).toContain("<script>alert(1)</script>");
  });
  it("shows every saved cell, including containers, leading zeros, empties and formulas", () => {
    const hidden = clone(cellSource);
    hidden.elements[0].hidden = true;
    const { container } = render(<NativeSourceViewer source={hidden} selected={null} citation={null} onPick={() => {}} />);
    for (const element of cellSource.elements) expect(container.querySelector(`[data-element-id="${element.element_id}"]`)).not.toBeNull();
    for (const element of cellSource.elements) if (element.cell?.formula) expect(container.textContent).toContain(element.cell.formula);
    expect(container.textContent).toContain("0012");
    expect(container.textContent).toContain("Empty cell");
    expect(container.textContent).toContain("Hidden source content");
  });
  it("groups CSV cells without a sheet container, preserving empty text and sheet navigation", () => {
    const source = clone(cellSource);
    source.elements = source.elements.filter((e) => e.kind === "cell").map((e, i) => ({ ...e, parent_id: null,
      locator: { kind: "cell", sheet: "CSV", cell: `${String.fromCharCode(65 + i)}1`, row: 1, column: i + 1 },
      cell: { ...e.cell!, value: { kind: "text", lexical: i === 1 ? "" : i === 0 ? "0012" : 'quoted, "value"' }, formula: null, cached_value: null, cached_state: "not_applicable" } }));
    source.total = source.elements.length;
    const pick = vi.fn();
    const { container } = render(<NativeSourceViewer source={source} selected={null} citation={null} onPick={pick} />);
    expect(container.querySelectorAll("table td")).toHaveLength(3);
    expect(container.querySelector('[data-element-id="cell2"] .native-lexical')?.textContent).toBe("");
    expect(container.textContent).toContain('quoted, "value"');
    fireEvent.change(screen.getByLabelText("Sheet"), { target: { value: elementKey(source.elements[0]) } });
    expect(pick).toHaveBeenCalledWith(source.elements[0]);
  });
  it("preserves Word block order, table nesting, headers and footers", () => {
    const source = clone(textSource);
    const template = source.elements[0];
    source.elements = [
      { id: "p1", parent: null, kind: "paragraph", part: "word/document.xml", path: "body/0", text: "First paragraph" },
      { id: "table", parent: null, kind: "table", part: "word/document.xml", path: "body/1", text: null },
      { id: "cell-p", parent: "table", kind: "paragraph", part: "word/document.xml", path: "body/1/r0/c0/0", text: "Table content" },
      { id: "p2", parent: null, kind: "paragraph", part: "word/document.xml", path: "body/2", text: "Last paragraph" },
      { id: "header", parent: null, kind: "paragraph", part: "word/header1.xml", path: "body/0", text: "Header content" },
      { id: "footer", parent: null, kind: "paragraph", part: "word/footer1.xml", path: "body/0", text: "Footer content" },
    ].map((row, i) => ({ ...template, element_id: row.id, parent_id: row.parent, kind: row.kind as "paragraph" | "table", order: i,
      text: row.text, locator: { kind: "word", part: row.part, structural_path: row.path, block_index: i } }));
    source.total = source.elements.length;
    const { container } = render(<NativeSourceViewer source={source} selected={null} citation={null} onPick={() => {}} />);
    expect([...container.querySelectorAll("[data-element-id]")].map((e) => e.getAttribute("data-element-id"))).toEqual(["p1", "table", "cell-p", "p2", "header", "footer"]);
    expect(container.querySelector(".native-word-table")?.textContent).toContain("Table content");
    expect(container.textContent).toContain("word/header1.xml"); expect(container.textContent).toContain("word/footer1.xml");
  });
  it("highlights only a supplied unique code-point span and discloses ambiguous citations", () => {
    const unique = fact.native_citations[0];
    const view = render(<NativeSourceViewer source={textSource} selected={elementKey(unique)} citation={unique} onPick={() => {}} />);
    expect(view.container.querySelector("mark")?.textContent).toBe(unique.quote);
    const panel = render(<NativeFactPanel result={original} source={textSource} selected={null} readOnly={false} onChanged={() => {}} onCitation={() => {}} />);
    expect(screen.getByRole("button", { name: `Code points [${unique.quote_span!.start}, ${unique.quote_span!.end})` })).toBeTruthy();
    panel.unmount();
    view.rerender(<NativeSourceViewer source={textSource} selected={elementKey(unique)} citation={{ ...unique, quote_match_count: 2, quote_span: null }} onPick={() => {}} />);
    expect(view.container.querySelector("mark")).toBeNull();
    const result = clone(original); result.native_facts[0].native_citations = [{ ...unique, quote_match_count: 2, quote_span: null }];
    render(<NativeFactPanel result={result} source={textSource} selected={null} readOnly={false} onChanged={() => {}} onCitation={() => {}} />);
    expect(screen.getByText(/quote occurs 2 times/)).toBeTruthy();
  });
  it("loads every page and rejects foreign publication or incomplete pages", async () => {
    const page = clone(cellSource);
    const result = { ...original, native_source: { reading_id: page.reading_id, bundle_sha256: page.bundle_sha256, publication_id: page.publication_id, source_sha256: page.source_sha256 }, result_version: page.result_version };
    const call = vi.spyOn(api, "nativeSources").mockResolvedValueOnce({ ...page, elements: page.elements.slice(0, 2), has_more: true, next_offset: 2 })
      .mockResolvedValueOnce({ ...page, elements: page.elements.slice(2), offset: 2, has_more: false });
    expect((await loadNativeSource(result)).elements).toHaveLength(page.elements.length);
    expect(call).toHaveBeenLastCalledWith(result.run_id, result.item_id, page.result_version, 2);
    call.mockResolvedValue({ ...page, publication_id: "foreign" });
    await expect(loadNativeSource(result)).rejects.toThrow("changed");
    call.mockResolvedValue({ ...page, total: page.total + 1 });
    await expect(loadNativeSource(result)).rejects.toThrow("incomplete");
  });
  it.each(["not_started", "running", "unpublished_failure", "rejected", "failed", "uncertain"] as const)("never mounts the PDF viewer for %s native outcomes", async (name) => {
    const result = fixtures.items[name] as NativeItemResult;
    vi.spyOn(api, "item").mockResolvedValue(result);
    vi.spyOn(api, "nativeSources").mockRejectedValue(new Error("Synthetic source unavailable"));
    const words = vi.spyOn(api, "words");
    const png = vi.spyOn(api, "pageUrl");
    render(<ItemReview wpId="synthetic" runId={result.run_id} itemId={result.item_id} approved={false} onChanged={() => {}} />);
    await screen.findByRole("heading", { name: "Native facts" });
    expect(words).not.toHaveBeenCalled(); expect(png).not.toHaveBeenCalled();
  });
});

describe("native human corrections", () => {
  it("retains exact null and empty text across reload; own-fact confirmation retains saved overrides", () => {
    setNativeField(key, 0, original.result_version!, fact.fact_id, "");
    setNativeField(key, 0, original.result_version!, "another", null);
    hydrateDrafts();
    expect(getDraft(key)?.nativeValues).toEqual({ [fact.fact_id]: "", another: null });
    const result = clone(original); result.correction.fields.saved = "0012";
    const body = nativeSaveBody(result, getDraft(key), fact.fact_id);
    expect(body.values).toEqual({ saved: "0012", [fact.fact_id]: "" });
    expect(body.confirm).toEqual([fact.fact_id]);
    expect(body.expected_result_version).toBe(original.result_version);
  });
  it("binds a source-only correction to its unchanged value without modifying the machine proposal", () => {
    const before = JSON.stringify(original.native_facts[0].proposal);
    setNativeSources(key, 0, original.result_version!, fact.fact_id, fact.proposal.citations);
    const body = nativeSaveBody(original, getDraft(key));
    expect(body.values).toEqual({ [fact.fact_id]: fact.effective_value });
    expect(body.native_sources[fact.fact_id]).toEqual(fact.proposal.citations);
    expect(JSON.stringify(original.native_facts[0].proposal)).toBe(before);
  });
  it("retains typing and citation changes made while saving; does not rebase across results", () => {
    setNativeField(key, 0, original.result_version!, fact.fact_id, "sent");
    const sent = getDraft(key);
    setNativeField(key, 0, original.result_version!, fact.fact_id, "typed later");
    settleNativeDraft(key, sent, 1, original.result_version!);
    expect(getDraft(key)?.nativeValues?.[fact.fact_id]).toBe("typed later");
    expect(getDraft(key)?.baseRevision).toBe(1);
    settleNativeDraft(key, getDraft(key), 2, "different");
    expect(getDraft(key)?.baseRevision).toBe(1);
    setNativeSources(key, 1, original.result_version!, fact.fact_id, fact.proposal.citations);
    const second = getDraft(key);
    setNativeSources(key, 1, original.result_version!, fact.fact_id, []);
    settleNativeDraft(key, second, 2, original.result_version!);
    expect(getDraft(key)?.nativeSources?.[fact.fact_id]).toEqual([]);
  });
  it("keeps a 409 draft and requires an explicit review of the refreshed revision", async () => {
    setNativeField(key, 0, original.result_version!, fact.fact_id, "human correction");
    const save = vi.spyOn(api, "saveNativeCorrection").mockRejectedValue(new ApiError(409, "revision_conflict", "Synthetic conflict"));
    const changed = vi.fn();
    const props = { result: original, source: textSource, selected: null, readOnly: false, onChanged: changed, onCitation: vi.fn() };
    const view = render(<NativeFactPanel {...props} />);
    fireEvent.click(screen.getByRole("button", { name: "Save corrections" }));
    await screen.findByText("Synthetic conflict");
    expect((screen.getByRole("button", { name: "I reviewed the refreshed correction" }) as HTMLButtonElement).disabled).toBe(true);
    expect(getDraft(key)?.nativeValues?.[fact.fact_id]).toBe("human correction");
    expect(changed).toHaveBeenCalledOnce(); expect(save).toHaveBeenCalledOnce();
    const updated = clone(original); updated.correction.revision = 2;
    view.rerender(<NativeFactPanel {...props} result={updated} />);
    expect((screen.getByRole("button", { name: "Save corrections" }) as HTMLButtonElement).disabled).toBe(true);
    fireEvent.click(screen.getByRole("button", { name: "I reviewed the refreshed correction" }));
    expect(getDraft(key)?.baseRevision).toBe(2);
    view.rerender(<NativeFactPanel {...props} result={{ ...updated, result_version: "new-publication" }} />);
    expect(screen.getByText(/draft belongs to an earlier result/)).toBeTruthy();
    expect((screen.getByRole("button", { name: "Save corrections" }) as HTMLButtonElement).disabled).toBe(true);
    expect(getDraft(key)?.nativeValues?.[fact.fact_id]).toBe("human correction");
  });
  it("does not attach an invalid source quote or mutate the original proposal", async () => {
    const before = JSON.stringify(original);
    vi.spyOn(api, "resolveNativeCitations").mockRejectedValue(new ApiError(422, "invalid", "Quote not in saved source"));
    render(<NativeFactPanel result={original} source={textSource} selected={elementKey(textSource.elements[0])} readOnly={false} onChanged={() => {}} onCitation={() => {}} />);
    const editor = within(document.querySelector(`[data-fact-id="${fact.fact_id}"]`)! as HTMLElement);
    fireEvent.click(editor.getByText("Edit source citations"));
    fireEvent.change(await editor.findByLabelText("Exact source quote"), { target: { value: "foreign quote" } });
    fireEvent.click(editor.getByRole("button", { name: "Check and attach source" }));
    await screen.findByText("Quote not in saved source");
    expect(getDraft(key)?.nativeSources?.[fact.fact_id]).toBeUndefined();
    hydrateDrafts();
    expect(getDraft(key)?.nativeCitationEdits?.[fact.fact_id].quote).toBe("foreign quote");
    expect(JSON.stringify(original)).toBe(before);
  });
  it("does not restore a discarded draft when citation checking completes later", async () => {
    const citation = fact.native_citations[0];
    let reply!: (value: { result_version: string; citations: typeof fact.native_citations }) => void;
    const pending = new Promise<{ result_version: string; citations: typeof fact.native_citations }>((resolve) => { reply = resolve; });
    const call = vi.spyOn(api, "resolveNativeCitations").mockReturnValue(pending);
    const show = vi.fn();
    render(<NativeFactPanel result={original} source={textSource} selected={elementKey(textSource.elements[0])}
      readOnly={false} onChanged={() => {}} onCitation={show} />);
    fireEvent.click(screen.getByText("Edit source citations"));
    fireEvent.change(await screen.findByLabelText("Exact source quote"), { target: { value: citation.quote } });
    fireEvent.click(screen.getByRole("button", { name: "Check and attach source" }));
    expect(call).toHaveBeenCalledOnce();
    fireEvent.click(screen.getByRole("button", { name: "Discard draft" }));
    expect(getDraft(key)).toBeUndefined();
    await act(async () => reply({ result_version: original.result_version!, citations: [citation] }));
    expect(getDraft(key)).toBeUndefined();
    expect(show).not.toHaveBeenCalled();
    hydrateDrafts();
    expect(getDraft(key)).toBeUndefined();
  });
  it.each(["quote", "source", "discard and re-enter"] as const)("retains a newer %s edit when an earlier citation check completes", async (change) => {
    const source = clone(textSource);
    source.elements.push({ ...source.elements[0], element_id: "another-saved-element", order: 1 });
    source.total = source.elements.length;
    const citation = fact.native_citations[0];
    let reply!: (value: { result_version: string; citations: typeof fact.native_citations }) => void;
    vi.spyOn(api, "resolveNativeCitations").mockReturnValue(new Promise((resolve) => { reply = resolve; }));
    const show = vi.fn();
    render(<NativeFactPanel result={original} source={source} selected={elementKey(source.elements[0])}
      readOnly={false} onChanged={() => {}} onCitation={show} />);
    fireEvent.click(screen.getByText("Edit source citations"));
    const quote = await screen.findByLabelText("Exact source quote");
    fireEvent.change(quote, { target: { value: citation.quote } });
    fireEvent.click(screen.getByRole("button", { name: "Check and attach source" }));
    if (change === "quote") fireEvent.change(quote, { target: { value: "New unchecked quote" } });
    else if (change === "source") fireEvent.change(screen.getByRole("combobox", { name: "Source element" }), { target: { value: elementKey(source.elements[1]) } });
    else {
      fireEvent.click(screen.getByRole("button", { name: "Discard draft" }));
      fireEvent.change(quote, { target: { value: citation.quote } });
    }
    const newer = getDraft(key)?.nativeCitationEdits?.[fact.fact_id];
    expect(newer).toBeDefined();
    await act(async () => reply({ result_version: original.result_version!, citations: [citation] }));
    expect(getDraft(key)?.nativeCitationEdits?.[fact.fact_id]).toEqual(newer);
    expect(getDraft(key)?.nativeSources?.[fact.fact_id]).toBeUndefined();
    expect(show).not.toHaveBeenCalled();
  });
  it("does not bind a pending citation after its effective value changes", async () => {
    const citation = fact.native_citations[0];
    let reply!: (value: { result_version: string; citations: typeof fact.native_citations }) => void;
    vi.spyOn(api, "resolveNativeCitations").mockReturnValue(new Promise((resolve) => { reply = resolve; }));
    const show = vi.fn();
    render(<NativeFactPanel result={original} source={textSource} selected={elementKey(textSource.elements[0])}
      readOnly={false} onChanged={() => {}} onCitation={show} />);
    fireEvent.click(screen.getByText("Edit source citations"));
    fireEvent.change(await screen.findByLabelText("Exact source quote"), { target: { value: citation.quote } });
    fireEvent.click(screen.getByRole("button", { name: "Check and attach source" }));
    fireEvent.change(screen.getByLabelText(`Effective value for ${fact.proposal.property} (${fact.fact_id})`), { target: { value: "0099" } });
    await act(async () => reply({ result_version: original.result_version!, citations: [citation] }));
    expect(screen.getByText("The value changed while its source was checked. Check the citation again.")).toBeTruthy();
    expect(getDraft(key)?.nativeValues?.[fact.fact_id]).toBe("0099");
    expect(getDraft(key)?.nativeSources?.[fact.fact_id]).toEqual([]);
    expect(getDraft(key)?.nativeCitationEdits?.[fact.fact_id].quote).toBe(citation.quote);
    expect(show).not.toHaveBeenCalled();
  });
  it("checks a manual quote before saving the human value and confirms only the chosen stable fact", async () => {
    const sourceCitation = fact.native_citations[0];
    vi.spyOn(api, "resolveNativeCitations").mockResolvedValue({ result_version: original.result_version!, citations: [sourceCitation] });
    const saved = clone(original); saved.correction.revision = 1;
    const save = vi.spyOn(api, "saveNativeCorrection").mockResolvedValue(saved);
    const changed = vi.fn();
    render(<NativeFactPanel result={original} source={textSource} selected={elementKey(textSource.elements[0])} readOnly={false} onChanged={changed} onCitation={() => {}} />);
    fireEvent.change(screen.getByLabelText(`Effective value for ${fact.proposal.property} (${fact.fact_id})`), { target: { value: "0099" } });
    fireEvent.click(screen.getByText("Edit source citations"));
    fireEvent.change(await screen.findByLabelText("Exact source quote"), { target: { value: sourceCitation.quote } });
    fireEvent.click(screen.getByRole("button", { name: "Check and attach source" }));
    await screen.findByText("Draft source", { exact: false });
    const confirm = screen.getByRole("button", { name: "Confirm this fact" }) as HTMLButtonElement;
    expect(confirm.disabled).toBe(false);
    fireEvent.click(confirm);
    await waitFor(() => expect(changed).toHaveBeenCalledOnce());
    expect(save).toHaveBeenCalledWith(original.run_id, original.item_id, expect.objectContaining({
      kind: "native", values: { [fact.fact_id]: "0099" }, confirm: [fact.fact_id], expected_result_version: original.result_version,
      native_sources: { [fact.fact_id]: [{ occurrence_id: sourceCitation.occurrence_id, element_id: sourceCitation.element_id, quote: sourceCitation.quote }] },
    }));
    expect(changed).toHaveBeenCalledOnce(); expect(getDraft(key)).toBeUndefined();
    expect(fact.proposal.value).toBe("0012");
  });
  it("uses the native facts result table when native facts are available", () => {
    expect(defaultResultTable(["documents", "native_facts", "file_names"])).toBe("native_facts");
    clearDraft(key);
  });
});
